# Area definition file

ease2_north_25km:
    hemisphere: north
    grid_tag: ease2north
    resolution_tag: 25km
    projection:
        proj: laea
        lat_0: 90.0
        lon_0: 0.0
        ellps: WGS84
        datum: WGS84
        units: m
    extent:
        xoff: 0
        yoff: 0
        xsize: 10800000
        ysize: 10800000
        dx: 25000
        dy: 25000
        numx: 432
        numy: 432
