# Definition file of supported auxiliary datasets in pysiral
---

# Note: path keywords must be set in local_machine_def.yaml

# list of valid auxiliary data types
auxdata_types:
    - mean_sea_surface
    - ice_concentration
    - ice_type
    - ice_type_fraction
    - snow_depth
    - snow_density


# list of mean_sea_surface data products
mss:

    # DTU 10 mean sea surface
    dtu10mss:
        pyclass: DTU1MinGrid
        docstr: DTU10 mean sea surface (1 minute grid)
        type: static
        frequency: null
        local_machine_directory: dtu_mss
        file: DTU10MSS_1min.nc
        source:
            transfer: ftp
            server: ftp.space.dtu.dk
            pwdfile: null
            link: /pub/DTU10/1_MIN/DTU10MSS_1min.nc


    # DTU 13 mean sea surface
    dtu13mss:
        pyclass: DTU1MinGrid
        docstr: DTU13 mean sea surface (1 minute grid)
        type: static
        frequency: null
        local_machine_directory: dtu_mss
        file: DTU13MSS_1min.nc
        source:
            transfer: ftp
            server: ftp.space.dtu.dk
            pwdfile: null
            link: /pub/DTU13/1_MIN/DTU13MSS_1min.nc