# Definition file of supported radar altimeter missions in pysiral
---

# -----------------------------------------------------------------------------
# Overview of radar avalailable radar altimeter mission and radar modes
# -----------------------------------------------------------------------------

# list of all mission
# (list item are the valid string tags for adressing the missions)
missions:
    - cryosat2
    - envisat
    - ers2
    - sentinel3a

# These missions are includeed in the pysiral concept but support
# will be added later in the development phase
missions_to_be_added:
    - ers1
    - altika

# list of supported radar altimeter modes
modes:
    - sar
    - sin
    - lrm

# Support for LRM data will come later with the integration of
# EnviSat and the ERS-1/2 mission
modes_to_be_added:
    - plrm


# -----------------------------------------------------------------------------
# Definition for each mission
# (the tag name has to be identical to the one in the mission list)
# -----------------------------------------------------------------------------

cryosat2:

    long_name: CryoSat-2
    docstr:
        Cryosphere radar altimeter mission of the European Space
        Agency (ESA)
    data_period:
        start: 2010-11-01T00:00:00.00+00
        stop: null
    sea_ice_radar_modes: ["sar", "sin"]
    orbit_max_latitude: 88.0
    options:
        ionospheric_correction_source:
            default: ionospheric_gim
            target: ionosphere
            type: selector
            options:
                - ionospheric_gim
                - ionospheric_mod
            docstr:
                Source of Ionospheric Correction
    settings:
        polar_threshold: 50.0
        max_connected_files_timedelta_seconds: 10
        max_inner_nonocean_segment_nrecords: 1000

envisat:

    long_name: Envisat

    docstr:
        Envisat (Enviromental Satellite) of the European Space
        Agency (ESA)

    data_period:
        start: 2002-05-14T00:00:00.00+00
        stop: 2012-03-31T23:59:59.99+00

    sea_ice_radar_modes: ["lrm"]

    orbit_max_latitude: 82.5

    settings:

        # Pre-Pocessor settings
        polar_threshold: 50.0
        max_connected_files_timedelta_seconds: 10
        max_inner_nonocean_segment_nrecords: 1000    

        # SGDR settings
        geophysical_correction_targets:

            range_correction:
                - dry_troposphere
                - inverse_barometric
                - wet_troposphere_model
                - wet_troposphere_mwr
                - ra2_ionosphere_ku
                - doris_ionosphere_ku
                - model_ionosphere_ku
                - sea_state_bias_ku
            
            geophysical_information:
                - total_geocentric_ocean_tide_1
                - total_geocentric_ocean_tide_2
                - ocean_tide_long_period
                - ocean_loading_tide_1
                - ocean_loading_tide_2
                - solid_earth_tide
                - geocentric_polar_tide

    options:

        geophysical_corrections:

            # For an unkown reason deepcopy fails if this tag does not exist
            default: null

            ionospheric_correction_source:
                selection: model_ionosphere_ku
                target: ionosphere
                type: selector
                options:
                    - ra2_ionosphere_ku
                    - doris_ionosphere_ku
                    - model_ionosphere_ku
                docstr:
                    Source of Ionospheric Correction in SGDR data

            wet_tropospheric_correction_source:
                selection: wet_troposphere_model
                target: wet_troposphere
                type: selector
                options:
                    - wet_troposphere_model
                    - wet_troposphere_mwr
                docstr:
                    Source of wet tropospheric correction in SGDR data

            tide_loading_source:
                selection: ocean_loading_tide_1
                target: ocean_loading_tide
                type: selector
                options:
                    - ocean_loading_tide_1
                    - ocean_loading_tide_2
                docstr:
                    Source of tide loading correction in SGDR data

            total_geocentric_ocean_tide_source:
                selection: total_geocentric_ocean_tide_1
                target: total_geocentric_ocean_tide
                type: selector
                options:
                    - total_geocentric_ocean_tide_1
                    - total_geocentric_ocean_tide_2
                docstr:
                    Source of total geocentric ocean tide correction in SGDR data

ers2:

    long_name: ERS-2

    docstr:
        ERS-2 of the European Space Agency (ESA)

    data_period:
        start: 1995-05-14T00:00:00.00+00
        stop: 2003-07-02T23:59:59.99+00

    sea_ice_radar_modes: ["lrm"]

    orbit_max_latitude: 82.5

    options: null

    settings:
        
        # Radar Altimeter Settings
        range_bin_width: 0.4545
        nominal_tracking_bin: 32.5

        # SGDR Input Settings
        n_blocks: 20

        range_correction_targets:
            dry_troposphere: model_dry_tropo_corr
            wet_troposphere: model_wet_tropo_corr
            inverse_barometric: inv_bar_corr
            dynamic_atmosphere: hf_fluctuations_corr
            ionosphere: iono_corr_model
            ocean_tide_elastic: ocean_tide_sol1
            ocean_tide_long_period: ocean_tide_equil
            ocean_loading_tide: load_tide_sol1
            solid_earth_tide: solid_earth_tide
            geocentric_polar_tide: pole_tide
            total_geocentric_ocean_tide: Null

        sgdr_timestamp_units: seconds since 1990-01-01 00:00:00
        sgdr_timestamp_calendar: gregorian

        # Pre-Processor Settings
        polar_threshold: 50.0
        max_connected_files_timedelta_seconds: 10
        max_inner_nonocean_segment_nrecords: 1000    


sentinel3a:

    long_name: Sentinel-3A

    docstr:
        Cryosphere radar altimeter mission of the European Space Agency (ESA)
    
    data_period:
        start: 2016-04-01T00:00:00.00+00
        stop: null
    
    sea_ice_radar_modes: ["sar"]
    
    orbit_max_latitude: 81.35
    
    settings:
        
        # Instrument Settings
        radar_mode: sar
        range_bin_width: 0.468465715626
        nominal_tracking_bin: 60

        # Dataset settings
        time_units: seconds since 2000-01-01 00:00:00.0
        time_calendar: gregorian

        # Metadata information
        xml_header_file: xfdumanifest.xml
        xml_metadata_object_index:
            processing: 0
            acquisitionPeriod: 1
            platform: 2
            generalProductInformation: 3
            measurementOrbitReference: 4
            measurementQualityInformation: 5
            measurementFrameSet: 6
            sralProductInformation: 7
    
        # Selection for geophysical corrections
        range_correction_targets:
            dry_troposphere: null
            wet_troposphere: null
            inverse_barometric: null
            dynamic_atmosphere: null
            ionosphere: null
            ocean_tide_elastic: null
            ocean_tide_long_period: null
            ocean_loading_tide: null
            solid_earth_tide: null
            geocentric_polar_tide: null
            total_geocentric_ocean_tide: null
        
        # Classifier
        classifier_targets:
            stack_standard_deviation: stdev_stack_l1b_echo_sar_ku
            stack_skewness: skew_stack_l1b_echo_sar_ku
            stack_kurtosis: kurt_stack_l1b_echo_sar_ku
            stack_maximum_power: max_stack_l1b_echo_sar_ku
            num_stack_waveforms: nb_stack_l1b_echo_sar_ku

        # Pre processors
        polar_threshold: 50.0
        max_connected_files_timedelta_seconds: 10
        max_inner_nonocean_segment_nrecords: 1000