# Definition file of supported radar altimeter missions in pysiral
---

# -----------------------------------------------------------------------------
# Overview of radar avalailable radar altimeter mission and radar modes
# -----------------------------------------------------------------------------

# list of all mission
# (list item are the valid string tags for adressing the missions)
missions:
    - cryosat2
    - envisat

# These missions are includeed in the pysiral concept but support
# will be added later in the development phase
missions_to_be_added:
    - ers1
    - ers2
    - altika

# list of supported radar altimeter modes
modes:
    - sar
    - sin
    - lrm

# Support for LRM data will come later with the integration of
# EnviSat and the ERS-1/2 mission
modes_to_be_added:
    - Null


# -----------------------------------------------------------------------------
# Definition for each mission
# (the tag name has to be identical to the one in the mission list)
# -----------------------------------------------------------------------------

cryosat2:

    long_name: CryoSat-2
    docstr:
        Cryosphere radar altimeter mission of the European Space
        Agency (ESA)
    data_period:
        start: 2010-11-01T00:00:00.00+00
        stop: null
    sea_ice_radar_modes: ["sar", "sin"]
    orbit_max_latitude: 88.0
    options:
        ionospheric_correction_source:
            default: ionospheric_gim
            target: ionosphere
            type: selector
            options:
                - ionospheric_gim
                - ionospheric_mod
            docstr:
                Source of Ionospheric Correction
    preproc:
        options:
            polar_threshold: 50.0
            max_connected_files_timedelta_seconds: 10
            max_inner_nonocean_segment_nrecords: 1000

envisat:

    long_name: Envisat

    docstr:
        Envisat (Enviromental Satellite) of the European Space
        Agency (ESA)

    data_period:
        start: 2006-01-01T00:00:00.00+00
        stop: 2012-03-31T23:59:59.99+00

    sea_ice_radar_modes: ["lrm"]

    orbit_max_latitude: 82.5

    options:

        polar_threshold: 50.0

        geophysical_corrections:

            # For an unkown reason deepcopy fails if this tag does not exist
            default: null

            ionospheric_correction_source:
                selection: model_ionosphere_ku
                target: ionosphere
                type: selector
                options:
                    - ra2_ionosphere_ku
                    - doris_ionosphere_ku
                    - model_ionosphere_ku
                docstr:
                    Source of Ionospheric Correction in SGDR data

            wet_tropospheric_correction_source:
                selection: wet_troposphere_model
                target: wet_troposphere
                type: selector
                options:
                    - wet_troposphere_model
                    - wet_troposphere_mwr
                docstr:
                    Source of wet tropospheric correction in SGDR data

            tide_loading_source:
                selection: ocean_loading_tide_1
                target: ocean_loading_tide
                type: selector
                options:
                    - ocean_loading_tide_1
                    - ocean_loading_tide_2
                docstr:
                    Source of tide loading correction in SGDR data

            total_geocentric_ocean_tide_source:
                selection: total_geocentric_ocean_tide_1
                target: total_geocentric_ocean_tide
                type: selector
                options:
                    - total_geocentric_ocean_tide_1
                    - total_geocentric_ocean_tide_2
                docstr:
                    Source of total geocentric ocean tide correction in SGDR data

ers2:

    long_name: ERS-2

    docstr:
        ERS-2 of the European Space Agency (ESA)

    data_period:
        start: 1995-05-14T00:00:00.00+00
        stop: 2003-07-02T23:59:59.99+00

    sea_ice_radar_modes: ["lrm"]

    orbit_max_latitude: 82.5

    options: null