# Definition file of parameters in pysiral


# categorical listing of all parameters with abbreviations, unit and docstr

l1b:

    timestamp:
        long_name: utc timestamp
        standard_name: timestamp
        units: seconds since 1970-01-01
        scale_factor: 1.0
        add_offset: 0.0

    longitude:
        long_name: longitude of satellite
        standard_name: longitude
        units: degrees
        coordinates: timestamp
        scale_factor: 1.0
        add_offset: 0.0

    latitude:
        long_name: latitude of satellite
        standard_name: latitude
        units: degrees
        coordinates: timestamp
        scale_factor: 1.0
        add_offset: 0.0

    altitude:
        long_name: altitude of satellite
        standard_name: altitude
        units: m
        coordinates: timestamp
        scale_factor: 1.0
        add_offset: 0.0


# A list of recognized identifiers for geophysical range corrections
correction_list:
    - dry_troposphere
    - wet_troposphere
    - inverse_barometric
    - dynamic_atmosphere
    - ionospheric
    - ocean_tide_elastic
    - ocean_tide_long_period
    - ocean_loading_tide
    - solid_earth_tide
    - geocentric_polar_tide

definition:

    # Geophysical parameters

    ice_freeboard:
        short_name: ifrb
        unit: meter
        level: L2
        docstr: Elevation of the ice surface above local sea level
        dtype: float32
        ascii_format: "%6.2f"

    snow_freeboard:
        short_name: sfrb
        level: L2
        unit: meter
        docstr: Elevation of the snow surface above local sea level
        dtype: float32
        ascii_format: "%6.2f"

    apparent_freeboard:
        short_name: afrb
        unit: meter
        level: L2
        docstr:
          Elevation above local sea level from the altimeter range
          without the geometrical correction for slower wave propagation
          in the snow layer
        dtype: float32
        ascii_format: "%6.2f"

    radar_freeboard:
        short_name: rfrb
        label: Radar Freeboard
        unit: meter
        dtype: float32
        cmap:
            name: viridis
            vmin: 0
            vmax: 0.4
            step: 0.1
        cmap_diff:
            name: bwr
            vmin: -0.10
            vmax: 0.10
            step: 0.05

    freeboard:
        short_name: frb
        label: Freeboard
        unit: meter
        dtype: float32
        cmap:
            name: viridis
            vmin: 0
            vmax: 0.5
            step: 0.1
        cmap_diff:
            name: coolwarm
            vmin: -0.20
            vmax: 0.20
            step: 0.10

    sea_surface_anomaly:
        short_name: ssa
        label: Sea Surface Anomaly
        unit: meter
        dtype: float32
        cmap:
            name: RdBu_r
            vmin: -1
            vmax: 1.0
            step: 0.5
        cmap_diff:
            name: bwr
            vmin: -0.5
            vmax: 0.5
            step: 0.25

    lead_fraction:
        short_name: lfr
        label: Lead Waveforms
        unit: fraction
        dtype: float32
        cmap:
            name: copper
            vmin: 0
            vmax: 0.50
            step: 0.1
        cmap_diff:
            name: bwr
            vmin: -0.25
            vmax: 0.25
            step: 0.1

    ice_fraction:
        short_name: ifr
        label: Ice Waveforms
        unit: fraction
        dtype: float32
        cmap:
            name: afmhot
            vmin: 0
            vmax: 1.0
            step: 0.2
        cmap_diff:
            name: bwr
            vmin: -0.25
            vmax: 0.25
            step: 0.1

    valid_fraction:
        short_name: vfr
        label: Valid Waveforms
        unit: fraction
        dtype: float32
        cmap:
            name: PiYG
            vmin: 0
            vmax: 1.0
            step: 0.2
        cmap_diff:
            name: bwr
            vmin: -0.25
            vmax: 0.25
            step: 0.1

    freeboard_uncertainty:
        short_name: frbunc
        label: Freeboard Uncertainty
        unit: meters
        dtype: float32
        cmap:
            name: rainbow
            vmin: 0
            vmax: 0.4
            step: 0.1
        cmap_diff:
            name: bwr
            vmin: -10.0
            vmax: 10.0
            step: 5

    freeboard_bias:
        short_name: frbb
        unit: meter
        level: L2
        docstr:
          Correlated bias of the freeboard value (to be associated with
          ice or snow freeboard only)
        dtype: float32
        ascii_format: "%6.2f"

    sea_surface_height:
        short_name: ssh
        label: Sea Surface Height
        unit: meters
        dtype: float32
        cmap:
            name: gist_earth
            vmin: -10
            vmax: 20
            step: 5.0
        cmap_diff:
            name: seismic
            vmin: -0.6
            vmax: 0.6
            step: 0.3

    sea_ice_thickness:
        short_name: sit
        label: Sea Ice Thickness
        unit: meters
        dtype: float32
        cmap:
            name: plasma
            vmin: 0
            vmax: 5.0
            step: 1.0
        cmap_diff:
            name: coolwarm
            vmin: -1.0
            vmax: 1.0
            step: 0.5

    sea_ice_thickness_uncertainty:
        short_name: situnc
        label: Thickness Uncertainty
        unit: meters
        dtype: float32
        cmap:
            name: rainbow
            vmin: 0
            vmax: 2.0
            step: 0.5
        cmap_diff:
            name: coolwarm
            vmin: -1.0
            vmax: 1.0
            step: 0.5

    sea_ice_concentration:
        short_name: sic
        label: Sea Ice Concentration
        unit: percent
        dtype: float32
        cmap:
            name: plasma
            vmin: 0
            vmax: 100.0
            step: 20.0
        cmap_diff:
            name: bwr
            vmin: -10.0
            vmax: 10.0
            step: 5

    sea_ice_type:
        short_name: sitype
        label: Sea Ice Type
        unit: fraction
        dtype: float32
        cmap:
            name: Spectral
            vmin: 0
            vmax: 1
            step: 0.25
        cmap_diff:
            name: bwr
            vmin: -1.0
            vmax: 1.0
            step: 0.5

    snow_depth:
        short_name: sd
        label: Snow Depth
        unit: meter
        dtype: float32
        cmap:
            name: cool
            vmin: 0
            vmax: 0.5
            step: 0.1
        cmap_diff:
            name: bwr
            vmin: -0.5
            vmax: 0.5
            step: 0.25