# Definition file of parameters in pysiral


# categorical listing of all parameters with abbreviations, unit and docstr

l1b:
    
    timestamp:
        long_name: utc timestamp
        standard_name: timestamp
        units: seconds since 1970-01-01
        scale_factor: 1.0
        add_offset: 0.0

    longitude:
        long_name: longitude of satellite
        standard_name: longitude
        units: degrees
        coordinates: timestamp
        scale_factor: 1.0
        add_offset: 0.0

    latitude:
        long_name: latitude of satellite
        standard_name: latitude
        units: degrees
        coordinates: timestamp
        scale_factor: 1.0
        add_offset: 0.0

    altitude:
        long_name: altitude of satellite
        standard_name: altitude
        units: m
        coordinates: timestamp
        scale_factor: 1.0
        add_offset: 0.0

#  Parameter definitions for Level-2 intermediate (l2i) output files
l2i:

    timestamp:
        long_name: utc timestamp
        standard_name: timestamp
        units: seconds since 1970-01-01
        scale_factor: 1.0
        add_offset: 0.0

    longitude:
        long_name: longitude of satellite / nadir measurement point
        standard_name: longitude
        units: degrees
        coordinates: timestamp
        scale_factor: 1.0
        add_offset: 0.0

    latitude:
        long_name: latitude of satellite / nadir measurement point
        standard_name: latitude
        units: degrees
        coordinates: timestamp
        scale_factor: 1.0
        add_offset: 0.0
    
    surface_type:
        long_name: "surface type flag (0: unknown, 1: ocean, 2: lead: 2, 3: polynya, 4: sea ice, 5: closed sea, 6: land ice, 7: land, 8: invalid)"
        standard_name: surface_tyoe
        units: flag
        coordinates: timestamp
        scale_factor: 1.0
        add_offset: 0.0

    elevation:
        long_name: "elevation of retracked point above WGS84 ellipsoid (= satellite altitude - range corrections - retracker range)"
        standard_name: elevation
        units: meter
        coordinates: timestamp
        scale_factor: 1.0
        add_offset: 0.0

    mean_sea_surface:
        long_name: "elevation of mean sea surface at measurement point (above WGS84 ellipsoid)"
        standard_name: mean_sea_surface
        units: meter
        coordinates: timestamp
        scale_factor: 1.0
        add_offset: 0.0

    sea_surface_anomaly:
        long_name: "departure of instantaneous sea surface height from mean sea surface height"
        standard_name: sea_surface_anomaly
        units: meter
        coordinates: timestamp
        scale_factor: 1.0
        add_offset: 0.0    

    radar_freeboard:
        long_name: "elevation of retracked point above instantaneous sea surface height (no snow range corrections)"
        standard_name: radar_freeboard
        units: meter
        coordinates: timestamp
        scale_factor: 1.0
        add_offset: 0.0

    freeboard:
        long_name: "elevation of retracked point above instantaneous sea surface height (with snow range corrections)"
        standard_name: freeboard
        units: meter
        coordinates: timestamp
        scale_factor: 1.0
        add_offset: 0.0    

    sea_ice_thickness:
        long_name: "thickness of the sea ice layer"
        standard_name: sea_ice_thickness
        units: meter
        coordinates: timestamp
        scale_factor: 1.0
        add_offset: 0.0        

    snow_depth:
        long_name: "thickness of the snow layer"
        standard_name: snow_depth
        units: meter
        coordinates: timestamp
        scale_factor: 1.0
        add_offset: 0.0     

    snow_density:
        long_name: "density of the snow layer"
        standard_name: snow_density
        units: kg/m^3
        coordinates: timestamp
        scale_factor: 1.0
        add_offset: 0.0     

    ice_density:
        long_name: "density of the sea ice layer"
        standard_name: ice_density
        units: kg/m^3
        coordinates: timestamp
        scale_factor: 1.0
        add_offset: 0.0  

    sea_ice_concentration:
        long_name: "sea ice concentration"
        standard_name: sea_ice_concentration
        units: percent
        valid_min: 0.0
        valid_max: 100.0
        coordinates: timestamp
        scale_factor: 1.0
        add_offset: 0.0  

    sea_ice_type:
        long_name: "fraction of multi-year ice (0: only first year ice, 1: only multi-year ice)"
        standard_name: sea_ice_type
        units: fraction
        valid_min: 0.0
        valid_max: 1.0
        coordinates: timestamp
        scale_factor: 1.0
        add_offset: 0.0 


# A list of recognized identifiers for geophysical range corrections
correction_list:
    - dry_troposphere
    - wet_troposphere
    - inverse_barometric
    - dynamic_atmosphere
    - ionospheric
    - ocean_tide_elastic
    - ocean_tide_long_period
    - ocean_loading_tide
    - solid_earth_tide
    - geocentric_polar_tide

definition:

    # Geophysical parameters

    ice_freeboard:
        short_name: ifrb
        unit: meter
        level: L2
        docstr: Elevation of the ice surface above local sea level
        dtype: float32
        ascii_format: "%6.2f"

    snow_freeboard:
        short_name: sfrb
        level: L2
        unit: meter
        docstr: Elevation of the snow surface above local sea level
        dtype: float32
        ascii_format: "%6.2f"

    apparent_freeboard:
        short_name: afrb
        unit: meter
        level: L2
        docstr:
          Elevation above local sea level from the altimeter range
          without the geometrical correction for slower wave propagation
          in the snow layer
        dtype: float32
        ascii_format: "%6.2f"

    radar_freeboard:
        short_name: rfrb
        unit: meter
        level: L2
        docstr:
          Elevation above local sea level from the altimeter range
          with the geometrical correction for slower wave propagation
          in the snow layer
        dtype: float32
        ascii_format: "%6.2f"

    freeboard:
        short_name: frb
        label: Freeboard
        unit: meter
        dtype: float32
        cmap:
            name: viridis
            vmin: 0
            vmax: 0.5
            step: 0.1
        cmap_diff:
            name: bwr
            vmin: -0.10
            vmax: 0.10
            step: 0.05

    sea_surface_anomaly:
        short_name: ssa
        label: Sea Surface Anomaly
        unit: meter
        dtype: float32
        cmap:
            name: RdBu_r
            vmin: -1
            vmax: 1.0
            step: 0.5
        cmap_diff:
            name: bwr
            vmin: -0.5
            vmax: 0.5
            step: 0.25

    lead_fraction:
        short_name: lfr
        label: Lead Waveforms
        unit: fraction
        dtype: float32
        cmap:
            name: afmhot
            vmin: 0
            vmax: 0.20
            step: 0.05
        cmap_diff:
            name: bwr
            vmin: -0.25
            vmax: 0.25
            step: 0.1

    ice_fraction:
        short_name: ifr
        label: Ice Waveforms
        unit: fraction
        dtype: float32
        cmap:
            name: afmhot
            vmin: 0
            vmax: 0.5
            step: 0.1
        cmap_diff:
            name: bwr
            vmin: -0.25
            vmax: 0.25
            step: 0.1

    valid_fraction:
        short_name: vfr
        label: Valid Waveforms
        unit: fraction
        dtype: float32
        cmap:
            name: rainbow
            vmin: 0
            vmax: 1.0
            step: 0.2
        cmap_diff:
            name: bwr
            vmin: -0.25
            vmax: 0.25
            step: 0.1

    freeboard_uncertainty:
        short_name: frbu
        unit: meter
        level: L2
        docstr:
          Uncorrelated uncertainty of the freeboard value (to be associated with
          ice or snow freeboard only)
        dtype: float32
        ascii_format: "%6.2f"

    freeboard_bias:
        short_name: frbb
        unit: meter
        level: L2
        docstr:
          Correlated bias of the freeboard value (to be associated with
          ice or snow freeboard only)
        dtype: float32
        ascii_format: "%6.2f"

    sea_ice_thickness:
        short_name: sit
        label: Sea Ice Thickness
        unit: meter
        dtype: float32
        cmap:
            name: plasma
            vmin: 0
            vmax: 5.0
            step: 1.0
        cmap_diff:
            name: bwr
            vmin: -1.0
            vmax: 1.0
            step: 0.5
