# Definition file of supported product output files in pysiral
---

# Example definition of an product definition file

# Level-2 files
level2:
    orbit_default:
        type: track
        format: hdf5
        filename_template: "{mission}{baseline}_{orbit}_{startdt}_{stopdt}_pysiral{pysiral_version}_l2.hdf"
        parameter_list:
            - timestamp
            - longitude
            - latitude
            - radar_freeboard
            - radar_freeboard_uncertainty
            - sea_surface_height
            - sea_surface_height_anomaly
            - surface_type
            - data_flag


